colorScheme: slate
defaultAppearance: dark
autoSwitchAppearance: true
enableSearch: false
enableCodeCopy: false

header:
  layout: basic
  showTitle: true

footer:
  showCopyright: true
  showThemeAttribution: true
  showAppearanceSwitcher: true
  showScrollToTop: true

homepage:
  layout: page
  showRecent: true

article:
  showDate: true
  showDateUpdated: true
  showAuthor: true
  showBreadcrumbs: false
  showDraftLabel: true
  showEdit: false
  editAppendPath: true
  showHeadingAnchors: true
  showPagination: true
  invertPagination: false
  showReadingTime: false
  showTableOfContents: false
  showTaxonomies: false
  showWordCount: false
  showComments: false

list:
  showBreadcrumbs: false
  showSummary: true
  showTableOfContents: false
  showTaxonomies: false
  groupByYear: true
  paginationWidth: 1

sitemap:
  excludedKinds:
    - taxonomy
    - term

taxonomy:
  showTermCount: true
